/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lurunfa_test_OpenCVHelper */

#ifndef _Included_com_lurunfa_test_OpenCVHelper
#define _Included_com_lurunfa_test_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lurunfa_test_OpenCVHelper
 * Method:    FindFeatures
 * Signature: (II[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_lurunfa_test_OpenCVHelper_FindFeatures
  (JNIEnv *, jobject, jint, jint, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
